# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EbuwLauqEFEuB4yUnlDKLDSucbQ4rHBN
"""

import torch
from flask import Flask, render_template, request, send_file
from diffusers import StableDiffusionPipeline
import os

app = Flask(__name__)

#  Detect if CUDA (GPU) is available
if torch.cuda.is_available():
    device = "cuda"
    dtype = torch.float16  # GPU supports float16
else:
    device = "cpu"
    dtype = torch.float32  # CPU needs float32

# Load Stable Diffusion pipeline
pipe1 = StableDiffusionPipeline.from_pretrained(
    "dreamlike-art/dreamlike-photoreal-2.0", torch_dtype=dtype
).to(device)

pipe2 = StableDiffusionPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0", torch_dtype=dtype
).to(device)

#  Merge models only if architectures match
if set(pipe1.unet.state_dict().keys()) == set(pipe2.unet.state_dict().keys()):
    print("Models are compatible. Merging...")
    merged_unet = {
        k: (0.5 * v + 0.5 * pipe2.unet.state_dict()[k]) for k, v in pipe1.unet.state_dict().items()
    }
    pipe1.unet.load_state_dict(merged_unet)
else:
    print(" Warning: Model architectures do not match! Using only dreamlike-photoreal-2.0.")

#  Function to generate and save image
def generate_image(prompt):
    image = pipe1(prompt).images[0]
    image_path = "static/generated_image.png"
    image.save(image_path)
    return image_path

@app.route("/", methods=["GET", "POST"])
def index():
    image_url = None

    if request.method == "POST":
        prompt = request.form["prompt"]
        image_url = generate_image(prompt)  # Generate image

    return render_template("index.html", image_url=image_url)

@app.route("/generated_image")
def get_generated_image():
    return send_file("static/generated_image.png", mimetype="image/png")

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0", port=5000)

#diffusers is a hugging face page for using diffusion models from huggingface hub
!pip install diffusers transformers accelerate









